name: sample_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - fastapi>=0.110.0
  - uvicorn>=0.27.0
  - tensorflow>=2.15.0,<2.16.0
  - numpy>=1.22.0
  - pandas=2.2.2
  - pillow>=10.0.0
  - pip
  - pip:
      - python-multipart>=0.0.9
      - tensorflow-io-gcs-filesystem==0.34.0
